// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXxqgApDP_2Pumkf7sCH-ZJYzM4sTdBU',
    appId: '1:178068463522:web:605ec72cdcb14b49185cfb',
    messagingSenderId: '178068463522',
    projectId: 'convey-7',
    authDomain: 'convey-7.firebaseapp.com',
    storageBucket: 'convey-7.firebasestorage.app',
    measurementId: 'G-090W6PER0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_coN9jLRT8rxFUbVPb12lRfSzlLmqwAs',
    appId: '1:178068463522:android:9bf7cb7f7497528b185cfb',
    messagingSenderId: '178068463522',
    projectId: 'convey-7',
    storageBucket: 'convey-7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA1-VyRJgh2k4GZ55IsfmTawL9MXEVBWw',
    appId: '1:178068463522:ios:d0cabc70146ca9a1185cfb',
    messagingSenderId: '178068463522',
    projectId: 'convey-7',
    storageBucket: 'convey-7.firebasestorage.app',
    iosBundleId: 'com.example.convey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA1-VyRJgh2k4GZ55IsfmTawL9MXEVBWw',
    appId: '1:178068463522:ios:d0cabc70146ca9a1185cfb',
    messagingSenderId: '178068463522',
    projectId: 'convey-7',
    storageBucket: 'convey-7.firebasestorage.app',
    iosBundleId: 'com.example.convey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVXxqgApDP_2Pumkf7sCH-ZJYzM4sTdBU',
    appId: '1:178068463522:web:342a43b16ef098de185cfb',
    messagingSenderId: '178068463522',
    projectId: 'convey-7',
    authDomain: 'convey-7.firebaseapp.com',
    storageBucket: 'convey-7.firebasestorage.app',
    measurementId: 'G-JQJ9N53BCW',
  );
}
